version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_task
  redis:
    image: redis:3
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 5s
      retries: 10
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      PORT: 3000
      NODE_ENV: development
      PROVIDER: LOCAL
      JWT_ACCESS_SECRET: ACCESS_SECRET
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_SECRET: REFRESH_SECRET
      JWT_REFRESH_EXPIRES_IN: 7d
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: users_task
      REDIS_URL: redis://redis:6379
      REDIS_DEFAULT_TTL: 60000
      ENV: DEV
      THROTTLE_MEDIUM_TTL: 10000 * 6
      THROTTLE_MEDIUM_LIMIT: 1000
    command: sh -c "npm run migration:run && npm start"